[clog]
repository = "https://github.com/jbellmann/play-with-clog"
changelog = "CHANGELOG.md"
subtitle = "Release Notes"

[sections]
Features = ["feat"]
Chore = ["chore"]
Performance = ["perf"]
Documentation = ["docs"]

[components]
README = ["long", "rme"]

